import assert from 'node:assert/strict';
import {createPreviewAuth,normalizePhone} from '../src/auth-preview.js';
assert.equal(normalizePhone('+964 771 234 5678'),'07712345678');
assert.equal(normalizePhone('٠٧٧١٢٣٤٥٦٧٨'),'07712345678');
assert.equal(normalizePhone('009647712345678'),'07712345678');
let time=1000,index=0;
const auth=createPreviewAuth({now:()=>time,makeCode:()=>['123456','654321','112233','445566','778899'][index++]});
const person={mode:'register',phone:'07712345678',name:'Test User',email:'TEST@example.com'};
assert.throws(()=>auth.start({...person,phone:'123'}),/عراقي/);
assert.throws(()=>auth.start({mode:'login',phone:person.phone}),/غير مسجّل/);
const first=auth.start(person);
assert.equal(first.previewCode,'123456');
assert.throws(()=>auth.verify('000000'),/غير صحيح/);
auth.cancel();
assert.throws(()=>auth.verify(first.previewCode),/جديد/);
assert.throws(()=>auth.start({mode:'login',phone:person.phone}),/غير مسجّل/,'Unverified registration must not create an account');
const second=auth.start(person);
assert.throws(()=>auth.resend(),/انتظر/);
time+=60000;
const resent=auth.resend();
assert.throws(()=>auth.verify(second.previewCode),/غير صحيح/,'Resend invalidates the old code');
const user=auth.verify(resent.previewCode);
assert.equal(user.email,'test@example.com');
assert.throws(()=>auth.verify(resent.previewCode),/جديد/,'Verified codes cannot be replayed');
assert.throws(()=>auth.start(person),/مسجّل بالفعل/);
assert.throws(()=>auth.start({...person,phone:'07812345678'}),/البريد مستخدم/);
const login=auth.start({mode:'login',phone:'+9647712345678'});
for(let attempt=0;attempt<5;attempt++)assert.throws(()=>auth.verify('000000'));
assert.throws(()=>auth.verify(login.previewCode),/عدد المحاولات/);
time+=60000;
const fresh=auth.resend();
time=fresh.expiresAt;
assert.throws(()=>auth.verify(fresh.previewCode),/صلاحية/);
// Successful returning login uses a new challenge and the verified identity.
const returning=createPreviewAuth({makeCode:()=> '012345'});
returning.start(person);returning.verify('012345');
returning.start({mode:'login',phone:person.phone});
assert.deepEqual(returning.verify('012345'),user);
const optional=createPreviewAuth({makeCode:()=> '012345'});
optional.start({...person,email:''});
assert.equal(optional.verify('012345').email,'');
optional.start({...person,phone:'07812345678',email:'  '});
assert.equal(optional.verify('012345').phone,'07812345678','Multiple accounts can omit email');
assert.throws(()=>optional.start({...person,phone:'07912345678',email:'invalid'}),/بريداً/);
const edited=optional.updateProfile({phone:person.phone,name:'Updated Name',email:' NEW@example.com '});
assert.equal(edited.email,'new@example.com');
optional.start({mode:'login',phone:person.phone});
assert.deepEqual(optional.verify('012345'),edited,'Returning login keeps profile edits');
assert.throws(()=>optional.updateProfile({phone:'07812345678',name:'Other User',email:edited.email}),/البريد مستخدم/);
assert.throws(()=>optional.updateProfile({...edited,name:'A'}),/الكامل/);
assert.throws(()=>optional.updateProfile({...edited,email:'bad'}),/بريداً/);
assert.equal(optional.updateProfile({...edited,email:''}).email,'','Profile email remains optional');
console.log('Phone normalization, verified registration, OTP expiry, retries, resend, cancellation and returning login checks passed.');

const passwordAuth=createPreviewAuth();
const passwordPerson={phone:'07787654321',name:'Password Person',email:'',password:'test-password'};
assert.throws(()=>passwordAuth.register({...passwordPerson,password:'short'}));
const passwordUser=passwordAuth.register(passwordPerson);
assert.throws(()=>passwordAuth.login({...passwordPerson,password:'wrong'}));
assert.deepEqual(passwordAuth.login({...passwordPerson,phone:'+9647787654321'}),passwordUser);
assert.throws(()=>passwordAuth.register(passwordPerson));
assert.equal('password' in passwordUser,false);

const reset=passwordAuth.start({mode:'reset',phone:passwordPerson.phone});
assert.throws(()=>passwordAuth.resetPassword('invalid','new-password'));
assert.throws(()=>passwordAuth.resetPassword(reset.previewCode,'short'));
passwordAuth.resetPassword(reset.previewCode,'new-password');
assert.throws(()=>passwordAuth.resetPassword(reset.previewCode,'other-password'));
assert.throws(()=>passwordAuth.login(passwordPerson));
assert.deepEqual(passwordAuth.login({...passwordPerson,password:'new-password'}),passwordUser);
const expiring=passwordAuth.start({mode:'reset',phone:passwordPerson.phone});
passwordAuth.cancel();assert.throws(()=>passwordAuth.resetPassword(expiring.previewCode,'new-password'));
