import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {createRouter,createMemoryHistory} from 'vue-router';
import {validatePartnership,emptyPartnership} from '../src/marketing/partnership-form.js';
import {filterArticles,articles} from '../src/marketing/articles.js';
import {pageMeta} from '../src/marketing/seo.js';
const valid={...emptyPartnership(),company:'Demo Company',name:'Demo User',email:'demo@example.com',phone:'+964 770 000 0000',website:'https://example.com',users:'under10k'};
assert.deepEqual(validatePartnership(valid),{});
assert.deepEqual(Object.keys(validatePartnership(emptyPartnership())).sort(),['company','email','name','phone','users']);
for(const field of ['company','name'])assert.ok(validatePartnership({...valid,[field]:'  '})[field]);
for(const email of ['x','@example.com','demo@','demo @example.com'])assert.ok(validatePartnership({...valid,email}).email);
for(const phone of ['abc12345','123','077٠٠٠٠٠٠٠٠'])assert.ok(validatePartnership({...valid,phone}).phone);
for(const website of ['javascript:alert(1)','ftp://example.com','example.com'])assert.ok(validatePartnership({...valid,website}).website);
assert.deepEqual(validatePartnership({...valid,website:''}),{});
assert.ok(validatePartnership({...valid,type:'invented'}).type);
assert.ok(validatePartnership({...valid,users:'invented'}).users);
assert.equal(filterArticles(articles,'التِّجارة','all').length,1);
assert.equal(filterArticles(articles,'الشرق الاوسط','digital').length,1);
assert.equal(filterArticles(articles,'مقال غير موجود','all').length,0);
assert.equal(filterArticles(articles,'','missing').length,0);
assert.equal(filterArticles(articles,'  ','all').length,1);
assert.equal(articles.length,1,'Do not invent archived articles');
const source=readFileSync('src/marketing/router.js','utf8');
const paths=[...source.matchAll(/path:'(\/ar[^']*)'/g)].map(m=>m[1]);
assert.equal(new Set(paths).size,6);assert.deepEqual(paths.sort(),Object.keys(pageMeta).sort());
const router=createRouter({history:createMemoryHistory(),routes:paths.map(path=>({path,component:{}}))});
for(const path of paths){await router.push(path);assert.equal(router.currentRoute.value.path,path);assert.equal(router.currentRoute.value.matched.length,1);assert.equal(router.resolve(path+'?type=host#contact').hash,'#contact')}
await router.push('/ar');await router.push('/ar/about');router.back();await new Promise(r=>setTimeout(r,10));assert.equal(router.currentRoute.value.path,'/ar');
assert.match(readFileSync('src/marketing/components.js','utf8'),/© 2026 Masal\. جميع الحقوق محفوظة\./);
console.log('Marketing tests passed: six routes, navigation history, Arabic article search, category filter and partnership validation.');
for(const name of readdirSync('src/marketing')){if(!/\.(js|json|css)$/.test(name))continue;const text=readFileSync('src/marketing/'+name,'utf8');assert.doesNotMatch(text,/ديجيتال|دجتل|Digital[ -]Zone|DIGITAL ZONE|سيف المفتي|رحال|تكت زون|سوبر كي/i,`Old brand reference in ${name}`)}
