import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {ref,computed,watch,nextTick,reactive,effectScope} from 'vue';
import {pageCount,clampPage,pageItems,pageNumbers} from '../src/pagination.js';
const items=Array.from({length:27},(_,id)=>({id}));
assert.equal(pageCount(0,8),1);
assert.equal(pageCount(27,8),4);
assert.deepEqual([1,2,3,4].flatMap(page=>pageItems(items,page,8)),items);
assert.equal(pageItems(items,4,8).length,3);
assert.equal(clampPage(4,3,8),1);
assert.equal(clampPage(0,27,8),1);
assert.deepEqual(pageItems([],9,8),[]);
assert.deepEqual(pageNumbers(1,20),[1,2,3,4,5]);
assert.deepEqual(pageNumbers(10,20),[8,9,10,11,12]);
assert.deepEqual(pageNumbers(20,20),[16,17,18,19,20]);
assert.deepEqual(pageNumbers(1,2),[1,2]);
console.log('Pagination boundaries, complete item coverage, shrinking lists and bounded page controls passed.');

const source=readFileSync(new URL('../src/PagedList.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'').replace('export default','return');
const component=Function('ref','computed','watch','nextTick','t','pageCount','clampPage','pageItems','pageNumbers',source)(ref,computed,watch,nextTick,text=>text,pageCount,clampPage,pageItems,pageNumbers);
const props=reactive({items,size:8,resetKey:'all',admin:false,scroll:false});
const scope=effectScope();
const pager=scope.run(()=>component.setup(props));
await pager.change(4);
assert.deepEqual(pager.visible.value,items.slice(24));
props.resetKey='games';await nextTick();
assert.equal(pager.current.value,1);
await pager.change(4);
props.items=items.slice(0,9);await nextTick();
assert.equal(pager.current.value,2);
assert.deepEqual(pager.visible.value,[items[8]]);
props.items=[];await nextTick();
assert.equal(pager.current.value,1);
assert.deepEqual(pager.visible.value,[]);
scope.stop();
console.log('Pagination component resets filters and clamps pages after data removal.');
