import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
const data=new Map();
globalThis.localStorage={getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};
const {middleSlides,slides,saveSlides,prepareSlide,MIDDLE_INTERVAL}=await import('../src/slides.js');
assert.equal(MIDDLE_INTERVAL,2000);
assert.equal(middleSlides.length,5);
assert.equal(slides.length,0);
for(const slide of middleSlides)assert.ok(existsSync('public/'+slide.src));
const reordered=[...middleSlides].reverse();
saveSlides(reordered,'middle');
assert.equal(middleSlides[0].id,reordered[0].id);
assert.equal(slides.length,0,'Middle updates do not change the top slider');
const reload=await import('../src/slides.js?reload');
assert.equal(reload.middleSlides[0].id,reordered[0].id);
const custom={id:'custom-banner',name:'Custom upload',src:'data:image/png;base64,AAAA'};
data.set('masal-middle-slider-v1',JSON.stringify([{id:'middle-hala',name:'Old offer',src:'middle-banners/hala.png'},custom]));
const migrated=await import('../src/slides.js?migrated');
assert.equal(migrated.middleSlides.length,6);
assert.equal(migrated.middleSlides[0].id,'middle-asiacell-25000');
assert.equal(migrated.middleSlides[5].id,custom.id,'Default banner updates preserve custom dashboard uploads');
saveSlides([],'middle');
const empty=await import('../src/slides.js?empty');
assert.equal(empty.middleSlides.length,0,'Deleting all images must not restore defaults');
localStorage.setItem=()=>{throw Error('quota');};
assert.throws(()=>saveSlides(reordered,'middle'),/مساحة/);
assert.equal(middleSlides.length,0,'Failed saves must not mutate the visible list');
globalThis.Image=class{width=10;height=10;async decode(){}};
globalThis.FileReader=class{readAsDataURL(file){file.arrayBuffer().then(bytes=>{this.result='data:'+file.type+';base64,'+Buffer.from(bytes).toString('base64');this.onload();});}};
const file=new File(['GIF89a-animation-bytes'],'animated.gif',{type:'image/gif'});
const prepared=await prepareSlide(file);
assert.equal(prepared.src,'data:image/gif;base64,'+Buffer.from(await file.arrayBuffer()).toString('base64'),'Animated bytes must not be flattened by canvas');
assert.equal(prepared.name,'animated.gif');
console.log('Middle slider defaults, separate storage, persistence, quota handling and GIF byte preservation passed.');
