import {ref} from 'vue';
import './about.css';
import {shared} from './components.js';
import {copy} from './content.js';
const milestones=[['٢٠٢٠','الانطلاق من بغداد',copy('بدأنا من قلب العراق'),'العراق'],['٢٠٢٢','الانضمام إلى كي كارد',copy('محطة كبرى حين'),'العراق'],['٢٠٢٣','إطلاق تكت زون',copy('وُلد تكت زون'),'العراق'],['٢٠٢٤','رحال وشريحة رحال الإلكترونية',copy('توسّعنا إلى حجز الفنادق'),'العراق'],['٢٠٢٦','التوسّع الإقليمي',copy('نتوسّع في الشرق الأوسط'),'العراق وقريباً المنطقة']];
const acquisition=[['Network','تكامل تقني',copy('ترقيات سلسلة'),'جاهزية ٩٩.٩٪'],['TrendingUp','نموّ في السوق',copy('زيادة في الإيرادات'),'مليون+ مستخدم في السنة الأولى'],['Handshake','شراكات موثوقة',copy('توسّع التعاون'),'تحالفات مع كبرى الشركات']];
const pillars=[['Lightbulb','الابتكار أولاً',copy('تقديم حلول تتجاوز'),['تخصيص وتوصيات مدعومة بالذكاء الاصطناعي','تطوير وتحسين مستمر للمنصّة','بنية تحتية قابلة للتوسّع لأحجام معاملات كبيرة']],['Heart','العميل في المركز',copy('نضع المستخدم'),['تسليم رقمي فوري','تجربة استخدام بسيطة وواضحة','توفّر ودعم على مدار الساعة']],['Globe','النمو بالشراكات',copy('نتوسّع عبر تعاون'),['تكامل مع شركات الاتصالات','شراكات في التقنية المالية','تحالفات وطنية لانتشار أوسع']]];
const values=[['Lightbulb','الابتكار',copy('نتجاوز الحدود')],['ShieldCheck','الثقة والأمان',copy('نضمن أن تكون')],['Users','العميل أولاً',copy('نصمّم تجارب')],['Handshake','التعاون',copy('نزداد قوّة')],['Sparkles','الأثر',copy('ندفع الشمول')]];
const achievements=[['٢٠٢٠','التأسيس في بغداد',copy('أطلقنا ديجيتال زون'),'البداية'],['٢٠٢١','أول مليون عملية',copy('تجاوزنا مليون'),'أول إنجاز'],['٢٠٢٢','الانضمام إلى كي كارد',copy('انضممنا إلى أكبر'),'النجاح الكبير'],['٢٠٢٣','إطلاق تكت زون ورحال',copy('دخلنا مجالي'),'توسّع الأعمال'],['٢٠٢٤','المنصّة الأولى في التجارة الرقمية',copy('حقّقنا موقع'),'ريادة السوق'],['٢٠٢٦','التوسّع الإقليمي',copy('وصلنا إلى أكثر'),'التوسّع']];
const certifications=[['CreditCard','المدفوعات الرقمية','حلول دفع آمنة وفورية لكل احتياجاتك الرقمية.','معتمد'],['ShieldCheck','متوافقون مع PCI-DSS',copy('نلتزم بالمعايير'),'معتمد'],['Award','معايير ISO',copy('متوافقون مع معايير'),'متوافق'],['Users','ثقة الملايين',copy('منصّة معروفة'),'مُستحَق']];
export default {components:shared,setup(){const vision=ref('vision'),flipped=ref(false);function profile(){const blob=new Blob(['ديجيتال زون\n\n'+copy('بدأت ديجيتال زون في العراق')+'\n\n'+copy('في عام ٢٠٢٢ أصبحت')+'\n\n'+copy('أن نكون الخدمة الرائدة')],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Digital-Zone-company-profile.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return {copy,milestones,acquisition,pillars,values,achievements,certifications,vision,flipped,profile}},template:`
<Hero class="dz-hero-compact" badge="من بغداد إلى المنطقة" title="كيف" accent="رقمَنّا" :description="copy('بدأت ديجيتال زون في العراق')" :primary="['شاهد قصّتنا',{path:'/ar/about',hash:'#journey'}]"><template #actions><button class="dz-button dz-outline" @click="profile">ملف الشركة <Icon name="Download" :size="17"/></button></template></Hero>
<section id="journey" class="dz-section"><div class="dz-container"><SectionHeading badge="رحلتنا" title="من الانطلاق إلى ملايين المستخدمين" :description="copy('اكتشف كيف نمت')"/><Timeline :items="milestones" grid/></div></section>
<section class="dz-section dz-soft"><div class="dz-container"><SectionHeading badge="شراكة استراتيجية" title="قصة الانضمام إلى كي كارد"/><div class="dz-acquisition-intro"><h3>تسريع الابتكار الرقمي عبر شراكة استراتيجية</h3><p>{{copy('في عام ٢٠٢٢ أصبحت')}}</p></div><div class="dz-grid dz-grid-3"><Card v-for="s in acquisition" :icon="s[0]" :title="s[1]" :description="s[2]" :stat="s[3]"/></div><QuoteCard :quote="copy('نحن سعداء بالانضمام')" name="سيف المفتي" role="الرئيس التنفيذي والمؤسس" class="dz-founder-quote"/></div></section>
<section class="dz-section"><div class="dz-container"><SectionHeading badge="ما يدفعنا إلى الأمام" title="الرؤية والرسالة"/><div class="dz-vision"><div class="dz-tabs" role="tablist" aria-label="الرؤية والرسالة"><button role="tab" :aria-selected="vision==='vision'" aria-controls="dz-vision-panel" :class="{selected:vision==='vision'}" @click="vision='vision'">Our Vision</button><button role="tab" :aria-selected="vision==='mission'" aria-controls="dz-vision-panel" :class="{selected:vision==='mission'}" @click="vision='mission'">Our Mission</button></div><div id="dz-vision-panel" role="tabpanel" class="dz-vision-panel"><h3>{{vision==='vision'?'نصنع المستقبل الرقمي':'العميل في المركز'}}</h3><p>{{vision==='vision'?copy('أن نكون الخدمة الرائدة'):copy('نضع المستخدم')}}</p></div></div><h3 class="dz-center dz-pillars-title" dir="ltr">Our Strategic Pillars</h3><div class="dz-grid dz-grid-3"><Card v-for="s in pillars" :icon="s[0]" :title="s[1]" :description="s[2]"><li v-for="line in s[3]">{{line}}</li></Card></div><div class="dz-about-stats"><StatBadge value="٣ ملايين+" label="عميل سعيد"/><StatBadge value="٥٠ مليون+" label="عملية ناجحة"/><StatBadge value="١٥+" label="شريك استراتيجي"/></div></div></section>
<section class="dz-section dz-soft"><div class="dz-container"><SectionHeading title="قيمنا الأساسية" :description="copy('المبادئ التي توجّه')"/><div class="dz-grid dz-grid-3 dz-values"><Card v-for="s in values" :icon="s[0]" :title="s[1]" :description="s[2]"/></div></div></section>
<section class="dz-section dz-soft"><div class="dz-container"><SectionHeading badge="التميّز والتقدير" title="أبرز المحطات والإنجازات" :description="copy('نحتفي برحلة')"/><Timeline :items="achievements"/><SectionHeading class="dz-security-heading" title="الاعتمادات الأمنية" :description="copy('حصلنا على شهادات')"/><div class="dz-grid dz-certifications"><Card v-for="s in certifications" :icon="s[0]" :title="s[1]" :description="s[2]" :badge="s[3]"/></div></div></section>
<section class="dz-section"><div class="dz-container"><SectionHeading title="فريق القيادة" description="القادة الذين يقودون رسالة ديجيتال زون في العراق."/><button class="dz-leader" :class="{'dz-flipped':flipped}" @click="flipped=!flipped" :aria-pressed="flipped" aria-label="سيف المفتي — اضغط لمعرفة المزيد"><div class="dz-leader-inner"><div class="dz-leader-front"><TeamArt/><h3>سيف المفتي</h3><p>الرئيس التنفيذي والمؤسس</p><span lang="en">Click to learn more</span></div><div class="dz-leader-back"><Icon name="Quote" :size="32"/><p>{{copy('نحن سعداء بالانضمام')}}</p><h3>سيف المفتي</h3><span>الرئيس التنفيذي والمؤسس</span></div></div></button></div></section>
<CTASection title="هل أنت مستعد للبدء؟" :description="copy('انضم إلى ملايين المستخدمين')" :primary="['كن شريكاً','/ar/business/partnerships']" :secondary="['استكشف منصّاتنا','/ar/mini-apps']"/>`};
