import {shared} from './components.js';
import './about.css';
const journey=[['01','اختيار البطاقة','عرض الشركات والفئات والأسعار ضمن كتالوج واضح.','البطاقات'],['02','تجربة الحساب','دخول كزائر أو إنشاء حساب باسم ورقم هاتف وبريد إلكتروني.','الحساب'],['03','إدارة المتجر','إدارة المنتجات والأسعار والمخزون والطلبات من لوحة موحّدة.','الإدارة'],['04','تجهيز الربط','استيراد البطاقات من Excel وتجهيز الربط مع المورّدين والدفع عبر Qi.','التكامل']];
const features=[['Smartphone','أرصدة الاتصالات','بطاقات زين وآسياسيل وغيرها، بفئات مختلفة.'],['Gamepad2','الألعاب والبطاقات العالمية','خيارات لشحن الألعاب والبطاقات الرقمية والاشتراكات.'],['Store','أصحاب المحلات','عرض أسعار المحلات ومتابعة طلباتها ضمن تجربة مرتبطة بالمتجر.']];
const values=[['Search','وضوح الاختيار','اسم البطاقة وفئتها وسعرها أمامك قبل تأكيد اختيارك.'],['Layers','إدارة موحّدة','المنتجات والمخزون والطلبات في لوحة واحدة.'],['Users','تجربة للجميع','حسابات للأفراد وأصحاب المحلات، مع إمكانية التصفح كزائر.'],['Smartphone','ويب + تطبيق','واجهة بسيطة قابلة للتثبيت كتطبيق PWA على جهازك.'],['Code','تجهيز التكامل','مصادر Excel وواجهات API والدفع عبر Qi ضمن خطة التطوير.']];
export default {components:shared,setup(){return {journey,features,values}},template:`
<Hero class="ms-hero-compact" badge="عن ماسال" title="بطاقاتك" accent="بمكان واحد" description="ماسال متجر للبطاقات الإلكترونية، يجمع أرصدة الاتصالات والألعاب والبطاقات العالمية والخدمات المحلية، للأفراد وأصحاب المحلات." :primary="['تصفح خدمات ماسال','/ar/mini-apps']" :secondary="['تعرّف على تجربة ماسال',{path:'/ar/about',hash:'#journey'}]"/>
<section id="journey" class="ms-section"><div class="ms-container"><SectionHeading badge="تجربة ماسال" title="تجربة واضحة من البداية" description="نطوّر تجربة تجمع اختيار البطاقات وإدارة المخزون ومتابعة الطلبات، مع تجهيز مصادر التزويد والدفع."/><Timeline :items="journey" grid/></div></section>
<section class="ms-section ms-soft"><div class="ms-container"><SectionHeading badge="البطاقات والخدمات" title="اختيارات تناسب احتياجاتك"/><div class="ms-grid ms-grid-3"><Card v-for="s in features" :icon="s[0]" :title="s[1]" :description="s[2]"/></div></div></section>
<section class="ms-section"><div class="ms-container"><SectionHeading badge="رؤيتنا" title="تجربة بسيطة وإدارة مرتّبة" description="أن تجد البطاقة المناسبة بسهولة، وأن يتمكّن صاحب المحل من متابعة نشاطه ضمن واجهة واضحة."/><div class="ms-about-stats"><StatBadge value="أفراد" label="شراء البطاقات"/><StatBadge value="PWA" label="قابل للتثبيت"/><StatBadge value="Qi" label="الدفع قيد التجهيز"/></div></div></section>
<section class="ms-section ms-soft"><div class="ms-container"><SectionHeading title="ما نهتم به في ماسال"/><div class="ms-grid ms-grid-3 ms-values"><Card v-for="s in values" :icon="s[0]" :title="s[1]" :description="s[2]"/></div></div></section>
<section class="ms-section"><div class="ms-container"><SectionHeading title="لأصحاب المحلات والمورّدين" description="تعاون في توفير البطاقات وتسعيرها وتجهيز مصادرها، حسب احتياجات نشاطك."/><div class="ms-grid ms-grid-2"><Card icon="Layers" title="استيراد Excel" description="تجهيز ملفات البطاقات ورفعها ضمن إدارة المخزون."/><Card icon="Code" title="ربط API" description="تجهيز مصادر التزويد بحسب توثيق المورّد وآلية عمله."/></div></div></section>
<CTASection title="تعرّف على ماسال" description="تصفح فئات البطاقات أو جهّز بيانات نشاطك لمناقشة خيارات الشراكة." :primary="['استكشف البطاقات','/ar/mini-apps']" :secondary="['كن شريكاً','/ar/business/partnerships']"/>`};
