import {shared} from './components.js';
import {copy,stats,miniStats,services,journey,partners} from './content.js';
export default {components:shared,setup(){return {copy,stats,miniStats,services,journey,partners}},template:`
<Hero badge="حلول الأعمال 🚀" title="اكتشف خدماتنا" accent="الرقمية" :description="copy('ماسال يجمع بطاقات الرصيد والألعاب والبطاقات العالمية في')" :primary="['اكتشف خدمات ماسال','/ar/mini-apps']" :secondary="['تعرّف على رحلتنا','/ar/about']" :stats="stats" decor/>
<section class="ms-section"><div class="ms-container"><SectionHeading badge="خدمات ماسال" title="احتياجاتك، وخدمات ماسال" :description="copy('افتح ماسال من المتصفح، وتصفّح البطاقات أو ثبّته على جها')"/><div class="ms-inline-stats"><StatBadge v-for="s in miniStats" :value="s[0]" :label="s[1]"/></div><div class="ms-grid ms-grid-3 ms-services"><Card v-for="s in services" :icon="s[0]" :title="s[1]" :description="s[2]" :badge="s[3]"/></div></div></section>
<section class="ms-section ms-story-section"><div class="ms-container ms-story ms-reveal"><div><span class="ms-badge ms-glass">بطاقاتك، بمكان واحد</span><h2>هذا هو ماسال</h2><p>{{copy('ماسال متجر للبطاقات الإلكترونية، يجمع أرصدة زين وآسياسي')}}</p><div class="ms-stats"><StatBadge value="أفراد" label="شراء البطاقات"/><StatBadge value="Qi" label="الدفع قيد التجهيز"/><StatBadge value="PWA" label="قابل للتثبيت"/></div><div class="ms-actions"><SiteLink to="/ar/about">تعرّف على ماسال</SiteLink><SiteLink to="/ar/mini-apps" outline>استكشف منصّاتنا</SiteLink></div></div><TeamArt/></div></section>
<section class="ms-section"><div class="ms-container"><SectionHeading badge="تجربتك مع ماسال" title="من اختيار البطاقة إلى متابعة الطلب" :description="copy('من اختيار البطاقة إلى متابعة الطلب، هدفنا أن تكون تجربة')"/><Timeline :items="journey"/></div></section>
<CTASection badge="اعمل معنا — شراكات استراتيجية" title="نبني مستقبل الخدمات الرقمية معاً" :primary="['كن شريكاً','/ar/business/partnerships']" :secondary="['تعرّف على شركائنا','/ar/business']"><div class="ms-grid ms-grid-3 ms-partner-icons"><Card v-for="s in partners" :icon="s[0]" :title="s[1]" :description="s[2]"/></div><template #bottom><p class="ms-trust">لأصحاب المحلات والمورّدين والمنصات الرقمية</p></template></CTASection>
<section class="ms-section"><div class="ms-container ms-download"><div><span class="ms-badge">البطاقات والخدمات</span><h2>ماسال على جهازك</h2><p>{{copy('افتح ماسال من المتصفح، وتصفّح البطاقات أو ثبّته على جها')}}</p><div class="ms-actions"><a class="ms-button" href="#/">افتح تطبيق ماسال ←</a><SiteLink to="/ar/mini-apps" outline>تصفح خدمات ماسال</SiteLink></div><RouterLink to="/ar/mini-apps" class="ms-text-link">استكشف منصّاتنا ←</RouterLink><div class="ms-inline-stats"><StatBadge v-for="s in stats" :value="s[0]" :label="s[1]"/></div></div><PhoneArt/></div></section>`};
