import {shared} from './components.js';
import {copy,stats,miniStats,services,journey,partners} from './content.js';
export default {components:shared,setup(){return {copy,stats,miniStats,services,journey,partners}},template:`
<Hero badge="حلول الأعمال 🚀" title="اكتشف خدماتنا" accent="الرقمية" :description="copy('From السفر')" :primary="['اكتشف تطبيقاتنا المصغّرة','/ar/mini-apps']" :secondary="['تعرّف على رحلتنا','/ar/about']" :stats="stats" english decor/>
<section class="dz-section"><div class="dz-container"><SectionHeading badge="تطبيقاتنا المصغّرة" title="احتياجاتك، وتطبيقاتنا المصغّرة" :description="copy('حمّل تطبيق سوبر كي')"/><div class="dz-inline-stats"><StatBadge v-for="s in miniStats" :value="s[0]" :label="s[1]"/></div><div class="dz-grid dz-grid-3 dz-services"><Card v-for="s in services" :icon="s[0]" :title="s[1]" :description="s[2]" :badge="s[3]"/></div></div></section>
<section class="dz-section dz-story-section"><div class="dz-container dz-story dz-reveal"><div><span class="dz-badge dz-glass">قصة نجاح رقمية</span><h2>قصة نجاحنا</h2><p>{{copy('بدأت ديجيتال زون منصّةً')}}</p><div class="dz-stats"><StatBadge value="٢٠٢٢" label="الانضمام إلى كي كارد"/><StatBadge value="٤" label="تطبيقات مصغّرة"/><StatBadge value="الأولى" label="منصّة في العراق"/></div><div class="dz-actions"><SiteLink to="/ar/about">اقرأ قصّتنا</SiteLink><SiteLink to="/ar/mini-apps" outline>استكشف منصّاتنا</SiteLink></div></div><TeamArt/></div></section>
<section class="dz-section"><div class="dz-container"><SectionHeading badge="محطات رحلتنا" title="من العراق إلى العالم" :description="copy('تأسّست ديجيتال زون لتقود التحوّل الرقمي في السوق العراقية. ومن')"/><Timeline :items="journey"/></div></section>
<CTASection badge="اعمل معنا — شراكات استراتيجية" title="نبني مستقبل الخدمات الرقمية معاً" :primary="['كن شريكاً','/ar/business/partnerships']" :secondary="['تعرّف على شركائنا','/ar/business']"><div class="dz-grid dz-grid-3 dz-partner-icons"><Card v-for="s in partners" :icon="s[0]" :title="s[1]" :description="s[2]"/></div><template #bottom><p class="dz-trust">تثق بنا أكثر من ١٠٠ علامة تجارية في العراق والمنطقة</p></template></CTASection>
<section class="dz-section"><div class="dz-container dz-download"><div><span class="dz-badge">التطبيقات المصغّرة</span><h2>رقمِن حياتك الآن</h2><p>{{copy('حمّل تطبيق سوبر كي')}}</p><div class="dz-actions"><a class="dz-button" href="https://apps.apple.com/" target="_blank" rel="noopener noreferrer"><Icon name="Apple" :size="18"/> حمّله من App Store</a><a class="dz-button dz-outline" href="https://play.google.com/" target="_blank" rel="noopener noreferrer"><Icon name="Play" :size="18"/> حمّله من Google Play</a></div><RouterLink to="/ar/mini-apps" class="dz-text-link">استكشف منصّاتنا ←</RouterLink><div class="dz-inline-stats"><StatBadge v-for="s in stats" :value="s[0]" :label="s[1]"/></div></div><PhoneArt/></div></section>`};
