import {ref,reactive,watch,nextTick} from 'vue';
import {useRoute} from 'vue-router';
import {shared} from './components.js';
import {copy} from './content.js';
import {emptyPartnership,validatePartnership} from './partnership-form.js';
const benefits=[['TrendingUp','نمو الإيرادات',copy('جهّز عرض البطاقات لعملائك وحدّد نموذج التسعير الذي يناس'),'نماذج تسعير مرنة'],['Code','تكامل سهل',copy('استيراد مخزون البطاقات من Excel وتجهيز الاتصال بمصادر A'),'حسب متطلبات المورّد'],['Headphones','دعم كامل',copy('متابعة متطلبات الشراكة وأسئلة الربط والتزويد، مع تحديد '),'آلية دعم واضحة']];
const steps=[['قدّم طلب الشراكة',copy('قدّم معلومات النشاط ونوع الشراكة ومصادر البطاقات التي ت')],['التقييم والاتفاق على الشروط',copy('نراجع احتياجات النشاط ونموذج التسعير وآلية التزويد قبل ')],['التكامل التقني',copy('يُجهّز الربط حسب توثيق المورّد، وتُختبر آلية الاستيراد ')],['الإطلاق والنمو معاً','بعد اكتمال الربط، تُراجع المخزونات والأسعار والطلبات وتُحدّد آلية متابعة التشغيل.']];
const quotes=[['موردو البطاقات',copy('جهّز المخزون للاستيراد من Excel أو ناقش إمكانات الربط ع'),'Excel + API'],['منصات الخدمات',copy('جهّز عرض بطاقات الرصيد والألعاب ضمن منصتك حسب متطلبات ا'),'ربط حسب المتطلبات']];
export default {components:shared,setup(){const route=useRoute(),dialog=ref(null),form=reactive(emptyPartnership()),errors=ref({}),reviewed=ref(false);watch(()=>route.query.type,t=>{if(['host','merchant','distributor'].includes(t))form.type=t},{immediate:true});function open(){errors.value={};reviewed.value=false;dialog.value.showModal()}function close(){dialog.value.close()}async function submit(){errors.value=validatePartnership(form);if(Object.keys(errors.value).length){await nextTick();dialog.value.querySelector('[aria-invalid="true"]')?.focus();return}reviewed.value=true;await nextTick();dialog.value.querySelector('[role="status"]')?.focus()}return {copy,benefits,steps,quotes,dialog,form,errors,reviewed,open,close,submit}},template:`
<Hero class="ms-hero-compact" badge="التالي: الشراكة" title="كن شريكاً" accent="لماسال" :description="copy('تعاون مع ماسال في توفير البطاقات الإلكترونية أو تجهيز م')" :primary="['ابدأ الشراكة',{path:'/ar/business/partnerships',hash:'#contact'}]" :secondary="['تعرّف على أعمالنا','/ar/business']"/>
<section class="ms-section"><div class="ms-container"><SectionHeading title="مزايا الشراكة" :description="copy('خيارات تعاون لموردي البطاقات والمنصات. تُحدّد الأسعار و')"/><div class="ms-grid ms-grid-3"><Card v-for="s in benefits" :icon="s[0]" :title="s[1]" :description="s[2]" :stat="s[3]"/></div></div></section>
<section class="ms-section ms-soft"><div class="ms-container"><SectionHeading badge="كيف تعمل الشراكة" title="عملية تكامل بسيطة" :description="copy('ابدأ بأربع خطوات')"/><NumberedSteps :items="steps"/></div></section>
<section id="contact" class="ms-section"><div class="ms-container"><SectionHeading title="هل أنت مستعد للبدء؟"/><div class="ms-contact-card ms-reveal"><span class="ms-icon"><Icon name="Rocket" :size="38"/></span><h3>ابدأ رحلة شركتك</h3><p>{{copy('جهّز بيانات نشاطك ونوع الشراكة التي تهمك لمناقشة متطلبا')}}</p><div class="ms-contact-notice"><Icon name="ShieldCheck"/><p>{{copy('نموذج محلي للمعاينة. لا تُرسل معلوماتك إلى أي جهة ولا ي')}}</p></div><button class="ms-button" @click="open">ابدأ مناقشة الشراكة ←</button><p class="ms-demo-note">نموذج للمعاينة: التحقق محلي فقط، ولا تُرسل معلوماتك إلى أي جهة.</p><small dir="ltr">MASAL · PARTNERSHIPS</small></div></div></section>
<section class="ms-section ms-soft"><div class="ms-container"><SectionHeading title="شراكات تناسب نشاطك" :description="copy('مجالان للتعاون مع ماسال، حسب طبيعة النشاط ومتطلبات توفير')"/><div class="ms-grid ms-grid-2"><QuoteCard v-for="q in quotes" :name="q[0]" :quote="q[1]" :stat="q[2]"/></div></div></section>
<dialog ref="dialog" class="ms-modal" aria-labelledby="ms-partnership-title"><button class="ms-close" @click="close" aria-label="إغلاق نموذج الشراكة"><Icon name="X"/></button><h2 id="ms-partnership-title">ابدأ رحلة شركتك</h2><template v-if="!reviewed"><p>نموذج للمعاينة: التحقق محلي فقط، ولا تُرسل معلوماتك إلى أي جهة.</p><form novalidate @submit.prevent="submit"><div class="ms-form-grid"><label v-for="field in [['company','اسم الشركة'],['name','الاسم الكامل'],['email','البريد الإلكتروني'],['phone','رقم الهاتف']]">{{field[1]}}<input v-model="form[field[0]]" :name="field[0]" :type="field[0]==='email'?'email':field[0]==='phone'?'tel':'text'" :autocomplete="{company:'organization',name:'name',email:'email',phone:'tel'}[field[0]]" :dir="['email','phone'].includes(field[0])?'ltr':undefined" :maxlength="field[0]==='phone'?22:150" required :aria-invalid="Boolean(errors[field[0]])" :aria-describedby="errors[field[0]]?'ms-error-'+field[0]:undefined"/><span v-if="errors[field[0]]" class="ms-error" :id="'ms-error-'+field[0]">{{errors[field[0]]}}</span></label></div><label>رابط المنصة (اختياري)<input v-model="form.website" type="url" name="website" dir="ltr" placeholder="https://example.com" maxlength="250" :aria-invalid="Boolean(errors.website)" :aria-describedby="errors.website?'ms-error-website':undefined"/><span v-if="errors.website" id="ms-error-website" class="ms-error">{{errors.website}}</span></label><div class="ms-form-grid"><label>نوع الشراكة<select v-model="form.type" required :aria-invalid="Boolean(errors.type)"><option value="host">استضافة التطبيقات المصغّرة</option><option value="merchant">شريك تجاري</option><option value="distributor">موزّع</option></select><span v-if="errors.type" class="ms-error">{{errors.type}}</span></label><label>قاعدة المستخدمين<select v-model="form.users" required :aria-invalid="Boolean(errors.users)" :aria-describedby="errors.users?'ms-error-users':undefined"><option value="" disabled>اختر حجم قاعدة المستخدمين</option><option value="under10k">أقل من 10,000</option><option value="10k100k">10,000 – 100,000</option><option value="100k1m">100,000 – 1,000,000</option><option value="over1m">أكثر من 1,000,000</option></select><span v-if="errors.users" id="ms-error-users" class="ms-error">{{errors.users}}</span></label></div><label>أهداف الشراكة (اختياري)<textarea v-model="form.message" rows="3" maxlength="2000"/></label><button class="ms-button" type="submit">معاينة الطلب ←</button></form></template><div v-else class="ms-form-receipt" role="status" tabindex="-1"><Icon name="CheckCircle2" :size="36"/><h3>المعلومات مكتملة</h3><p>{{form.company}} · {{form.name}}</p><p>تم التحقق من الطلب محلياً. لم تُرسل المعلومات أو يُسجّل طلب لدى ماسال.</p><button class="ms-button" @click="close">إغلاق</button></div></dialog>`};
