import {ref,reactive,watch,nextTick} from 'vue';
import {useRoute} from 'vue-router';
import {shared} from './components.js';
import {copy} from './content.js';
import {emptyPartnership,validatePartnership} from './partnership-form.js';
const benefits=[['TrendingUp','نمو الإيرادات',copy('احصل على مصادر دخل'),'٢٥–٤٠٪ متوسط حصة الإيرادات'],['Code','تكامل سهل',copy('تكامل سلس عبر واجهات'),'أقل من أسبوعين مدة التكامل'],['Headphones','دعم كامل',copy('مدير حساب مخصّص'),'٢٤/٧ دعم متواصل']];
const steps=[['قدّم طلب الشراكة',copy('املأ نموذج الشراكة')],['التقييم والاتفاق على الشروط',copy('نحدّد موعد جلسة')],['التكامل التقني',copy('يوفّر فريقنا التقني')],['الإطلاق والنمو معاً',copy('انطلق بتطبيقات ديجيتال')]];
const quotes=[['SuperApp MENA',copy('رفع التكامل'),'+٣٥٪ زيادة في الإيرادات'],['MobileHub',copy('كان الربط سلساً'),'+٥٠٪ تفاعل المستخدمين'],['QuickPay Gulf',copy('من تقديم الطلب'),'١٠ أيام حتى الإطلاق']];
export default {components:shared,setup(){const route=useRoute(),dialog=ref(null),form=reactive(emptyPartnership()),errors=ref({}),reviewed=ref(false);watch(()=>route.query.type,t=>{if(['host','merchant','distributor'].includes(t))form.type=t},{immediate:true});function open(){errors.value={};reviewed.value=false;dialog.value.showModal()}function close(){dialog.value.close()}async function submit(){errors.value=validatePartnership(form);if(Object.keys(errors.value).length){await nextTick();dialog.value.querySelector('[aria-invalid="true"]')?.focus();return}reviewed.value=true;await nextTick();dialog.value.querySelector('[role="status"]')?.focus()}return {copy,benefits,steps,quotes,dialog,form,errors,reviewed,open,close,submit}},template:`
<Hero class="dz-hero-compact" badge="التالي: الشراكة" title="كن شريكاً" accent="لديجيتال زون" :description="copy('استضف تطبيقات ديجيتال زون المصغّرة داخل')" :primary="['ابدأ الشراكة',{path:'/ar/business/partnerships',hash:'#contact'}]" :secondary="['تعرّف على أعمالنا','/ar/business']"/>
<section class="dz-section"><div class="dz-container"><SectionHeading title="مزايا الشراكة" :description="copy('انضم إلى منظومة مُجرَّبة')"/><div class="dz-grid dz-grid-3"><Card v-for="s in benefits" :icon="s[0]" :title="s[1]" :description="s[2]" :stat="s[3]"/></div></div></section>
<section class="dz-section dz-soft"><div class="dz-container"><SectionHeading badge="كيف تعمل الشراكة" title="عملية تكامل بسيطة" :description="copy('ابدأ بأربع خطوات')"/><NumberedSteps :items="steps"/></div></section>
<section id="contact" class="dz-section"><div class="dz-container"><SectionHeading title="هل أنت مستعد للبدء؟"/><div class="dz-contact-card dz-reveal"><span class="dz-icon"><Icon name="Rocket" :size="38"/></span><h3>ابدأ رحلة شركتك</h3><p>{{copy('أرسل لنا بياناتك')}}</p><div class="dz-contact-notice"><Icon name="ShieldCheck"/><p>{{copy('بياناتك محمية')}}</p></div><button class="dz-button" @click="open">ابدأ مناقشة الشراكة ←</button><p class="dz-demo-note">نموذج للمعاينة: التحقق محلي فقط، ولا تُرسل معلوماتك إلى أي جهة.</p><small dir="ltr">By clicking this button, you agree to our partnership evaluation process.</small></div></div></section>
<section class="dz-section dz-soft"><div class="dz-container"><SectionHeading title="نجاح شركائنا" :description="copy('اطّلع على النمو')"/><div class="dz-grid dz-grid-3"><QuoteCard v-for="q in quotes" :name="q[0]" :quote="q[1]" :stat="q[2]"/></div></div></section>
<dialog ref="dialog" class="dz-modal" aria-labelledby="dz-partnership-title" @click="e=>{if(e.target===dialog)close()}"><button class="dz-close" @click="close" aria-label="إغلاق نموذج الشراكة"><Icon name="X"/></button><h2 id="dz-partnership-title">ابدأ رحلة شركتك</h2><template v-if="!reviewed"><p>نموذج للمعاينة: التحقق محلي فقط، ولا تُرسل معلوماتك إلى أي جهة.</p><form novalidate @submit.prevent="submit"><div class="dz-form-grid"><label v-for="field in [['company','اسم الشركة'],['name','الاسم الكامل'],['email','البريد الإلكتروني'],['phone','رقم الهاتف']]">{{field[1]}}<input v-model="form[field[0]]" :name="field[0]" :type="field[0]==='email'?'email':field[0]==='phone'?'tel':'text'" :autocomplete="{company:'organization',name:'name',email:'email',phone:'tel'}[field[0]]" :dir="['email','phone'].includes(field[0])?'ltr':undefined" :maxlength="field[0]==='phone'?22:150" required :aria-invalid="Boolean(errors[field[0]])" :aria-describedby="errors[field[0]]?'dz-error-'+field[0]:undefined"/><span v-if="errors[field[0]]" class="dz-error" :id="'dz-error-'+field[0]">{{errors[field[0]]}}</span></label></div><label>رابط المنصة (اختياري)<input v-model="form.website" type="url" name="website" dir="ltr" placeholder="https://example.com" maxlength="250" :aria-invalid="Boolean(errors.website)" :aria-describedby="errors.website?'dz-error-website':undefined"/><span v-if="errors.website" id="dz-error-website" class="dz-error">{{errors.website}}</span></label><div class="dz-form-grid"><label>نوع الشراكة<select v-model="form.type" required :aria-invalid="Boolean(errors.type)"><option value="host">استضافة التطبيقات المصغّرة</option><option value="merchant">شريك تجاري</option><option value="distributor">موزّع</option></select><span v-if="errors.type" class="dz-error">{{errors.type}}</span></label><label>قاعدة المستخدمين<select v-model="form.users" required :aria-invalid="Boolean(errors.users)" :aria-describedby="errors.users?'dz-error-users':undefined"><option value="" disabled>اختر حجم قاعدة المستخدمين</option><option value="under10k">أقل من 10,000</option><option value="10k100k">10,000 – 100,000</option><option value="100k1m">100,000 – 1,000,000</option><option value="over1m">أكثر من 1,000,000</option></select><span v-if="errors.users" id="dz-error-users" class="dz-error">{{errors.users}}</span></label></div><label>أهداف الشراكة (اختياري)<textarea v-model="form.message" rows="3" maxlength="2000"/></label><button class="dz-button" type="submit">معاينة الطلب ←</button></form></template><div v-else class="dz-form-receipt" role="status" tabindex="-1"><Icon name="CheckCircle2" :size="36"/><h3>المعلومات مكتملة</h3><p>{{form.company}} · {{form.name}}</p><p>تم التحقق من الطلب محلياً. لم تُرسل المعلومات أو يُسجّل طلب لدى ديجيتال زون.</p><button class="dz-button" @click="close">إغلاق</button></div></dialog>`};
