import {ref,computed,onMounted,onBeforeUnmount,nextTick} from 'vue/dist/vue.esm-bundler.js';
import {LayoutDashboard,Layers,ShoppingBag,Users,Store,Wallet,CreditCard,Headphones,BarChart3,Settings,Package,Upload,Link,Search,ChevronLeft,Plus,X,ArrowUpLeft,Download,Menu,CheckCircle2,AlertCircle,Clock,Eye,Pencil,Globe,ArrowRight} from 'lucide-vue-next';
import {store,number,isoDate,record} from './store.js';
import {validateInventory} from './inventory.js';
import {readInventory,exportWorkbook} from './spreadsheets.js';
import './dashboard.css';
import SliderManager from './SliderManager.js';
const importedCodes=new Set();
const sections=[
  {id:'overview',name:'لوحة التحكم',icon:LayoutDashboard},
  {id:'cards',name:'البطاقات والأسعار',icon:CreditCard},
  {id:'inventory',name:'المخزون والاستيراد',icon:Package},
  {id:'orders',name:'الطلبات والمبيعات',icon:ShoppingBag},
  {id:'customers',name:'إدارة العملاء',icon:Users},
  {id:'merchants',name:'أصحاب المحلات',icon:Store},
  {id:'payments',name:'المدفوعات وQi',icon:Wallet},
  {id:'suppliers',name:'المورّدون وAPI',icon:Link},
  {id:'support',name:'الدعم والتذاكر',icon:Headphones},
  {id:'reports',name:'التقارير',icon:BarChart3},
  {id:'slider',name:'السلايدر',icon:Layers},
  {id:'settings',name:'الإعدادات',icon:Settings},
];
export default {
  components:{SliderManager,Layers,ShoppingBag,Users,Store,Wallet,CreditCard,Headphones,BarChart3,Settings,Package,Upload,Link,Search,ChevronLeft,Plus,X,ArrowUpLeft,Download,Menu,CheckCircle2,AlertCircle,Clock,Eye,Pencil,Globe,ArrowRight},
  setup(){
    const section=ref('overview'),mobileMenu=ref(false),query=ref(''),filter=ref('الكل'),period=ref('الكل'),notice=ref(''),modal=ref(null),dialog=ref(null),draft=ref({}),formError=ref(''),fileInput=ref(null),preview=ref(null),importing=ref(false),settings=ref({...store.settings});
    let noticeTimer;
    function syncRoute(){const id=location.hash.split('/')[2]||'overview';section.value=sections.some(s=>s.id===id)?id:'overview';query.value='';filter.value='الكل';mobileMenu.value=false;window.scrollTo({top:0,behavior:'instant'});}
    function go(id){location.hash='/admin/'+id;}
    function notify(text){notice.value=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.value='',4000);}
    onMounted(()=>{syncRoute();window.addEventListener('hashchange',syncRoute);});
    onBeforeUnmount(()=>{window.removeEventListener('hashchange',syncRoute);clearTimeout(noticeTimer);});
    const title=computed(()=>sections.find(s=>s.id===section.value).name);
    const matches=text=>String(text).toLowerCase().includes(query.value.toLowerCase());
    const cards=computed(()=>store.products.filter(p=>matches(p.name+' '+p.en)&&(filter.value==='الكل'||p.category===filter.value)));
    const orders=computed(()=>store.orders.filter(o=>matches(o.id+' '+o.name+' '+o.customer)&&(filter.value==='الكل'||o.status===filter.value)&&(period.value==='الكل'||o.date===isoDate())));
    const people=computed(()=>store.customers.filter(c=>matches(c.name+' '+c.email+' '+c.phone)&&(section.value!=='merchants'||c.kind==='محل')));
    const tickets=computed(()=>store.tickets.filter(t=>matches(t.subject+' '+t.customer+' '+t.id)&&(filter.value==='الكل'||t.status===filter.value)));
    const gross=computed(()=>store.orders.filter(o=>o.status==='مكتمل').reduce((s,o)=>s+o.price,0));
    const stock=computed(()=>store.products.reduce((s,p)=>s+p.stock.reduce((a,b)=>a+b,0),0));
    const stockRows=computed(()=>store.products.flatMap(p=>p.values.map((value,i)=>({product:p,value,index:i,quantity:p.stock[i]}))));
    const lowStock=computed(()=>stockRows.value.filter(r=>r.quantity<=store.settings.lowStock));
    const openTickets=computed(()=>store.tickets.filter(t=>t.status!=='مغلقة').length);
    const stats=computed(()=>[
      {label:'المبيعات التجريبية',value:number(gross.value),unit:'د.ع',note:'قيمة الطلبات المكتملة',icon:Wallet,section:'reports'},
      {label:'إجمالي الطلبات',value:number(store.orders.length),note:'طلبات هذه الجلسة',icon:ShoppingBag,section:'orders'},
      {label:'الكارتات المتوفرة',value:number(stock.value),note:number(store.products.filter(p=>p.active).length)+' بطاقات منشورة',icon:CreditCard,section:'inventory'},
      {label:'العملاء والمحلات',value:number(store.customers.length),note:number(store.customers.filter(c=>c.kind==='محل').length)+' حساب محل',icon:Users,section:'customers'},
      {label:'تذاكر تحتاج متابعة',value:number(openTickets.value),note:'فريق الدعم',icon:Headphones,section:'support'},
    ]);
    const categorySales=computed(()=>['اتصالات','ألعاب','عالمية'].map(name=>({name,total:store.orders.filter(o=>o.status==='مكتمل'&&store.products.find(p=>p.id===o.productId)?.category===name).reduce((s,o)=>s+o.price,0)})));
    const topProducts=computed(()=>store.products.map(p=>({...p,sold:store.orders.filter(o=>o.productId===p.id&&o.status==='مكتمل').reduce((s,o)=>s+o.quantity,0)})).sort((a,b)=>b.sold-a.sold).slice(0,5));
    async function show(type,item){formError.value='';modal.value=type;
      if(type==='product')draft.value=item?JSON.parse(JSON.stringify(item)):{name:'',en:'',category:'اتصالات',color:'#9b4a66',tag:'بطاقة جديدة',active:true,values:[5000],prices:[5250],wholesale:[5100],stock:[0]};
      else if(type==='customer')draft.value=item?{...item}:{name:'',phone:'',email:'',kind:section.value==='merchants'?'محل':'فرد',active:true,discount:0};
      else if(type==='supplier')draft.value=item?{...item}:{name:'',url:'',method:'Excel',active:true};
      else draft.value={...item};
      await nextTick();dialog.value.showModal();
    }
    function close(){dialog.value?.close();modal.value=null;}
    function save(){
      const d=draft.value;formError.value='';
      if(modal.value==='product'){
        if(!d.name.trim()||!d.en.trim()||!d.values.length||d.values.some((v,i)=>!(Number(v)>0)||!(Number(d.prices[i])>0)||!(Number(d.wholesale[i])>0))||new Set(d.values.map(Number)).size!==d.values.length){formError.value='اكتب اسم البطاقة وفئات وأسعار صحيحة بدون فئات مكررة.';return;}
        const data={...d,name:d.name.trim(),en:d.en.trim(),values:d.values.map(Number),prices:d.prices.map(Number),wholesale:d.wholesale.map(Number)};
        if(d.id){const old=store.products.find(p=>p.id===d.id);if(old.values.some((v,i)=>!data.values.includes(v)&&(old.stock[i]>0||store.orders.some(o=>o.productId===d.id&&o.value===v)))){formError.value='الفئة مرتبطة بمخزون أو طلب، تگدر تغيّر سعرها وتخلي قيمتها.';return;}data.stock=data.values.map(v=>old.stock[old.values.indexOf(v)]||0);Object.assign(old,data);}else{data.id=Math.max(...store.products.map(p=>p.id),0)+1;data.stock=data.values.map(()=>0);store.products.push(data);}
        record('تم تحديث كتالوج البطاقات');
      }else if(modal.value==='customer'){
        if(!d.name.trim()||!/^\+?[0-9\s()-]{7,20}$/.test(d.phone)||!d.email.trim()){formError.value='اكتب معلومات العميل كاملة ورقماً بالأرقام الإنجليزية.';return;}
        if(store.customers.some(c=>c.id!==d.id&&c.email.toLowerCase()===d.email.toLowerCase().trim())){formError.value='الإيميل موجود بحساب آخر.';return;}
        if(d.id)Object.assign(store.customers.find(c=>c.id===d.id),d);else store.customers.push({...d,id:crypto.randomUUID(),date:isoDate()});record('تم تحديث بيانات حساب تجريبي');
      }else if(modal.value==='supplier'){
        if(d.method==='API'&&d.url&&!/^https:\/\//.test(d.url)){formError.value='رابط API لازم يبدأ بـ https://';return;}
        if(d.id)Object.assign(store.suppliers.find(v=>v.id===d.id),d);else store.suppliers.push({...d,id:crypto.randomUUID()});record('تم تحديث مورّد تجريبي');
      }else if(modal.value==='ticket'){
        Object.assign(store.tickets.find(t=>t.id===d.id),{reply:d.reply,status:d.status});record('تم تحديث تذكرة '+d.id);
      }
      notify('تم الحفظ داخل الجلسة التجريبية');close();
    }
    function addDenom(){draft.value.values.push(0);draft.value.prices.push(0);draft.value.wholesale.push(0);draft.value.stock.push(0);}
    function removeDenom(i){if(draft.value.values.length<2)return;if(draft.value.id&&store.orders.some(o=>o.productId===draft.value.id&&o.value===draft.value.values[i])){formError.value='هذه الفئة مرتبطة بطلب. تگدر تعدّل سعرها وتخليها بالبطاقة.';return;}if(draft.value.stock[i]>0){formError.value='هذه الفئة بيها مخزون. خليها بالبطاقة.';return;}for(const key of ['values','prices','wholesale','stock'])draft.value[key].splice(i,1);}
    function toggleProduct(p){p.active=!p.active;record((p.active?'نشر':'إيقاف')+' بطاقة '+p.name);}
    async function loadFile(event){const file=event.target.files?.[0];if(!file)return;importing.value=true;preview.value=null;try{const rows=await readInventory(file);preview.value={...validateInventory(rows,store.products,importedCodes),name:file.name,total:rows.length};if(!rows.length)notify('الملف ما بيه كارتات.');}catch(e){notify(e.message||'تعذّرت قراءة الملف.');}finally{importing.value=false;event.target.value='';}}
    function confirmImport(){if(!preview.value?.accepted.length)return;const checked=validateInventory(preview.value.accepted.map(r=>({product_id:r.productId,denomination:r.value,code:r.code})),store.products,importedCodes);for(const r of checked.accepted){store.products.find(p=>p.id===r.productId).stock[r.index]++;importedCodes.add(r.code);}store.imports.unshift({id:crypto.randomUUID(),name:preview.value.name,count:checked.accepted.length,rejected:preview.value.errors.length+checked.errors.length,date:isoDate()});record('استيراد '+checked.accepted.length+' كارت تجريبي');notify('تمت إضافة الكارتات المقبولة للمخزون');preview.value=null;}
    async function template(){try{await exportWorkbook('masal-inventory-template.xlsx',['product_id','denomination','code'],[[1,5000,'DEMO-CARD-0001'],[1,5000,'DEMO-CARD-0002'],[2,10000,'DEMO-CARD-0003']]);}catch{notify('تعذّر تنزيل القالب');}}
    async function exportReport(){try{await exportWorkbook('masal-orders-'+isoDate()+'.xlsx',['Order ID','Date','Card','Value','Quantity','Total IQD','Customer','Type','Status'],orders.value.map(o=>[o.id,o.date,o.name,o.value,o.quantity,o.price,o.customer,o.kind,o.status]));notify('تم تجهيز تقرير Excel');}catch{notify('تعذّر تصدير التقرير');}}
    function saveSettings(){Object.assign(store.settings,settings.value);record('تم تحديث إعدادات المتجر التجريبية');notify('تم حفظ إعدادات هذه الجلسة');}
    function updateStatus(order){record('تحديث حالة '+order.id+' إلى '+order.status);}
    return {store,number,isoDate,sections,section,title,mobileMenu,query,filter,period,notice,modal,dialog,draft,formError,fileInput,preview,importing,settings,cards,orders,people,tickets,gross,stock,stockRows,lowStock,openTickets,stats,categorySales,topProducts,go,notify,show,close,save,addDenom,removeDenom,toggleProduct,loadFile,confirmImport,template,exportReport,saveSettings,updateStatus};
  },
  template:`<div class="admin-shell">
  <button v-if="mobileMenu" class="admin-overlay" @click="mobileMenu=false" aria-label="إغلاق قائمة الإدارة"></button>
  <aside class="admin-sidebar" :class="{'is-open':mobileMenu}"><a href="#/admin" class="admin-brand"><span><Layers :size="25"/></span><div>ماسال<small>BUSINESS CONSOLE</small></div></a><div class="admin-nav-label">مساحة الإدارة</div><nav><button v-for="s in sections" :key="s.id" :class="{active:section===s.id}" :aria-current="section===s.id?'page':undefined" @click="go(s.id)"><component :is="s.icon" :size="18"/><span>{{s.name}}</span><ChevronLeft :size="14"/></button></nav><div class="admin-side-bottom"><a href="#"><Globe :size="17"/> فتح المتجر <ArrowUpLeft :size="15"/></a><div class="admin-demo-pill"><span></span> لوحة إدارة تجريبية</div><small dir="ltr">MASAL / VUE PWA</small></div></aside>
  <main class="admin-main"><header class="admin-header"><div><button class="admin-menu-button" @click="mobileMenu=!mobileMenu" aria-label="قائمة الإدارة"><Menu :size="22"/></button><span>مساحة العمل <ChevronLeft :size="13"/> <b>{{title}}</b></span></div><div class="admin-header-right"><span class="admin-live"><i></i> الجلسة جاهزة</span><a href="#">زيارة التطبيق <ArrowUpLeft :size="15"/></a><span class="admin-avatar">م</span></div></header>
  <div class="admin-content"><div class="admin-live-strip"><b>الأحداث المباشرة</b><span><i></i>{{store.events[0]?.text||'لوحة ماسال جاهزة لأول حركة تشغيلية'}}</span><small dir="ltr">{{store.events[0]?.date.slice(11,16)||'LIVE'}}</small></div>
  <section v-if="section==='overview'" class="admin-hero"><div><span dir="ltr">{{isoDate()}} / MASAL CONSOLE</span><h1>أهلاً بيك، كل متجرك قدّامك.</h1><p>البطاقات، المحلات والطلبات… كل التفاصيل بمكان واحد.</p></div><div><button @click="go('inventory')"><Upload :size="17"/> استيراد الكارتات</button><a href="#"><Globe :size="17"/> فتح التطبيق</a></div></section>
  <div v-else class="admin-page-heading"><div><span class="admin-eyebrow">MASAL / BUSINESS</span><h1>{{title}}</h1><p>{{section==='cards'?'تحكّم بالفئات وأسعار الأفراد والمحلات.':section==='inventory'?'تابع الكميات واستورد ملفات الكارتات.':section==='support'?'طلبات المساعدة القادمة من التطبيق.':'بيانات متجرك، مرتبة وواضحة.'}}</p></div><button v-if="section==='cards'" class="admin-primary" @click="show('product')"><Plus :size="17"/> إضافة بطاقة</button><button v-if="section==='customers'||section==='merchants'" class="admin-primary" @click="show('customer')"><Plus :size="17"/> إضافة {{section==='merchants'?'محل':'عميل'}}</button><button v-if="section==='suppliers'" class="admin-primary" @click="show('supplier')"><Plus :size="17"/> إضافة مورّد</button><button v-if="section==='orders'||section==='reports'" class="admin-secondary" @click="exportReport"><Download :size="17"/> تصدير Excel</button></div>
  <SliderManager v-if="section==='slider'"/><div v-if="section!=='slider'" class="admin-session-note"><AlertCircle :size="15"/> بيانات هذه اللوحة مرتبطة بمعاينة التطبيق داخل نفس التبويب. التغييرات تبقى خلال الجلسة وتُصفّر عند تحديث الصفحة.</div>
  <template v-if="section==='overview'">
    <div class="admin-stats"><button v-for="s in stats" @click="go(s.section)"><div><span>{{s.label}}</span><component :is="s.icon" :size="18"/></div><strong dir="ltr">{{s.value}} <small>{{s.unit}}</small></strong><p>{{s.note}}</p></button></div>
    <div class="admin-two-columns"><section class="admin-panel"><div class="admin-panel-title"><h2>المبيعات حسب التصنيف</h2><button @click="go('reports')">عرض التقرير <ArrowUpLeft :size="15"/></button></div><div class="admin-sales-summary"><div><span>إجمالي المبيعات التجريبية</span><strong dir="ltr">{{number(gross)}} <small>IQD</small></strong><small>لا توجد عمليات دفع حقيقية</small></div><div class="admin-category-bars"><div v-for="c in categorySales"><span>{{c.name}}<b dir="ltr">{{number(c.total)}}</b></span><i><span :style="{width:(gross?c.total/gross*100:0)+'%'}"></span></i></div></div></div></section>
    <section class="admin-panel"><div class="admin-panel-title"><h2>حالة المخزون والربط</h2><button @click="go('inventory')">إدارة المخزون <ArrowUpLeft :size="15"/></button></div><div class="admin-health"><div><span class="admin-health-icon"><Package/></span><span>فئات تحتاج تزويد<small>حد التنبيه {{number(store.settings.lowStock)}} كارتات</small></span><b>{{number(lowStock.length)}}</b></div><div><span class="admin-health-icon"><CreditCard/></span><span>الدفع بواسطة Qi<small>جاهز لتجهيز الربط الفعلي</small></span><em>غير مربوط</em></div><div><span class="admin-health-icon"><Link/></span><span>مورّدو API<small>إعدادات معاينة فقط</small></span><b>{{number(store.suppliers.filter(v=>v.method==='API').length)}}</b></div></div></section></div>
    <section class="admin-panel"><div class="admin-panel-title"><h2>آخر الطلبات</h2><button @click="go('orders')">عرض كل الطلبات <ArrowUpLeft :size="15"/></button></div><div v-if="!store.orders.length" class="admin-empty"><ShoppingBag/><h3>أول طلب يبدأ الحكاية</h3><p>جرّب شراء بطاقة من التطبيق، وراح تظهر هنا مباشرة.</p><a href="#" class="admin-secondary">فتح التطبيق <ArrowUpLeft :size="15"/></a></div><div v-else class="admin-table-wrap"><table><thead><tr><th>الطلب</th><th>البطاقة</th><th>العميل</th><th>المبلغ</th><th>الحالة</th></tr></thead><tbody><tr v-for="o in store.orders.slice(0,5)"><td dir="ltr">{{o.id}}</td><td>{{o.name}}</td><td>{{o.customer}}</td><td dir="ltr">{{number(o.price)}} IQD</td><td><span class="admin-status">{{o.status}}</span></td></tr></tbody></table></div></section>
    <div class="admin-two-columns"><section class="admin-panel"><div class="admin-panel-title"><h2>بطاقاتك الأكثر طلباً</h2><button @click="go('cards')">عرض البطاقات</button></div><div class="admin-ranking" v-for="(p,i) in topProducts"><span class="admin-rank">{{i+1}}</span><span class="admin-card-logo" :style="{color:p.color}">{{p.en}}</span><div>{{p.name}}<small>{{p.category}}</small></div><b>{{number(p.sold)}} <small>كارت</small></b></div></section><section class="admin-panel"><div class="admin-panel-title"><h2>آخر النشاطات</h2><span>هذه الجلسة</span></div><div v-if="!store.events.length" class="admin-empty compact"><Clock/><p>راح يظهر نشاط المتجر هنا.</p></div><div class="admin-event" v-for="e in store.events.slice(0,5)"><i></i><span>{{e.text}}<small dir="ltr">{{e.date.slice(0,10)}} · {{e.date.slice(11,16)}}</small></span></div></section></div>
  </template>
  <template v-if="section==='cards'"><div class="admin-toolbar"><div class="admin-search"><Search :size="18"/><input v-model="query" placeholder="ابحث عن بطاقة أو شركة..." aria-label="البحث في البطاقات"/></div><select v-model="filter" aria-label="تصنيف البطاقات"><option v-for="c in ['الكل','اتصالات','ألعاب','عالمية']">{{c}}</option></select><span>{{number(cards.length)}} بطاقات</span></div><section class="admin-panel"><div class="admin-table-wrap"><table><thead><tr><th>البطاقة</th><th>التصنيف</th><th>الفئات</th><th>سعر الأفراد من</th><th>سعر المحلات من</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody><tr v-for="p in cards"><td><div class="admin-card-cell"><span :style="{color:p.color}">{{p.en}}</span><div>{{p.name}}<small dir="ltr">ID / {{p.id}}</small></div></div></td><td>{{p.category}}</td><td>{{number(p.values.length)}}</td><td dir="ltr">{{number(Math.min(...p.prices))}} IQD</td><td dir="ltr">{{number(Math.min(...p.wholesale))}} IQD</td><td><button class="admin-status" :class="{muted:!p.active}" @click="toggleProduct(p)" :aria-label="(p.active?'إيقاف ':'نشر ')+p.name">{{p.active?'منشورة':'موقوفة'}}</button></td><td><button class="admin-row-action" @click="show('product',p)" :aria-label="'تعديل '+p.name"><Pencil :size="16"/> تعديل</button></td></tr></tbody></table><div v-if="!cards.length" class="admin-empty compact">ما لقينا بطاقة بهالبحث.</div></div></section></template>
  <template v-if="section==='inventory'"><div class="admin-mini-stats"><div><span>إجمالي المخزون</span><b>{{number(stock)}}</b></div><div><span>فئات منخفضة</span><b>{{number(lowStock.length)}}</b></div><div><span>دفعات الاستيراد</span><b>{{number(store.imports.length)}}</b></div></div><section class="admin-panel admin-import-panel"><div><span class="admin-import-icon"><Upload :size="28"/></span><h2>استيراد الكارتات من Excel</h2><p>نزّل القالب، عبّي معرف البطاقة والفئة والكود، ثم ارفع الملف للمعاينة.</p><small>ملفات XLSX حتى 2 MB و5000 كارت. استخدم أكواداً تجريبية؛ لا تُرسل الملفات إلى خادم.</small></div><div class="admin-import-actions"><button class="admin-primary" :disabled="importing" @click="fileInput.click()"><Upload :size="17"/> {{importing?'قراءة الملف...':'اختيار ملف Excel'}}</button><button class="admin-secondary" @click="template"><Download :size="17"/> تنزيل القالب</button><input ref="fileInput" type="file" accept=".xlsx" hidden @change="loadFile"/></div></section>
    <section v-if="preview" class="admin-panel"><div class="admin-panel-title"><h2>معاينة {{preview.name}}</h2><button @click="preview=null">إلغاء</button></div><div class="admin-preview-counts"><span>{{number(preview.total)}} صف</span><span>{{number(preview.accepted.length)}} مقبول</span><span>{{number(preview.errors.length)}} مرفوض</span></div><ul class="admin-import-errors" v-if="preview.errors.length"><li v-for="e in preview.errors.slice(0,10)">صف {{e.row}}: {{e.reason}}</li></ul><button class="admin-primary" :disabled="!preview.accepted.length" @click="confirmImport">إضافة الصفوف المقبولة للمخزون</button></section>
    <section class="admin-panel"><div class="admin-panel-title"><h2>مخزون الفئات</h2><span>المتاح في الجلسة</span></div><div class="admin-table-wrap"><table><thead><tr><th>البطاقة</th><th>معرف البطاقة</th><th>الفئة</th><th>المتاح</th><th>الحالة</th></tr></thead><tbody><tr v-for="r in stockRows"><td>{{r.product.name}}</td><td>{{r.product.id}}</td><td>{{number(r.value)}}</td><td>{{number(r.quantity)}}</td><td><span class="admin-status" :class="{warning:r.quantity<=store.settings.lowStock}">{{r.quantity===0?'نفد المخزون':r.quantity<=store.settings.lowStock?'منخفض':'متوفر'}}</span></td></tr></tbody></table></div></section><section class="admin-panel"><div class="admin-panel-title"><h2>سجل الاستيراد</h2></div><div v-if="!store.imports.length" class="admin-empty compact">ماكو دفعات مستوردة بعد.</div><div class="admin-import-log" v-for="batch in store.imports"><span>{{batch.name}}<small dir="ltr">{{batch.date}}</small></span><b>{{number(batch.count)}} مقبول / {{number(batch.rejected)}} مرفوض</b></div></section>
  </template>
  <template v-if="section==='orders'||section==='reports'"><div v-if="section==='reports'" class="admin-mini-stats"><div><span>مبيعات مكتملة</span><b>{{number(gross)}} <small>IQD</small></b></div><div><span>متوسط الطلب</span><b>{{number(store.orders.filter(o=>o.status==='مكتمل').length?Math.round(gross/store.orders.filter(o=>o.status==='مكتمل').length):0)}} <small>IQD</small></b></div><div><span>الكارتات المباعة</span><b>{{number(store.orders.filter(o=>o.status==='مكتمل').reduce((s,o)=>s+o.quantity,0))}}</b></div></div><div class="admin-toolbar"><div class="admin-search"><Search :size="18"/><input v-model="query" placeholder="ابحث برقم الطلب، العميل أو البطاقة..." aria-label="البحث في الطلبات"/></div><select v-model="filter" aria-label="حالة الطلب"><option v-for="s in ['الكل','مكتمل','قيد المراجعة','ملغي']">{{s}}</option></select><select v-model="period" aria-label="فترة الطلبات"><option>الكل</option><option>اليوم</option></select></div><section class="admin-panel"><div v-if="!orders.length" class="admin-empty"><ShoppingBag/><h3>ماكو طلبات بهالاختيار</h3><p>جرّب طلباً من التطبيق أو غيّر الفلتر.</p><a href="#" class="admin-secondary">فتح التطبيق</a></div><div v-else class="admin-table-wrap"><table><thead><tr><th>الطلب / التاريخ</th><th>البطاقة</th><th>العميل</th><th>الكمية</th><th>المبلغ</th><th>الحالة</th><th></th></tr></thead><tbody><tr v-for="o in orders"><td><span dir="ltr">{{o.id}}</span><small dir="ltr">{{o.date}}</small></td><td>{{o.name}}<small>{{number(o.value)}}</small></td><td>{{o.customer}}<small>{{o.kind}}</small></td><td>{{number(o.quantity)}}</td><td dir="ltr">{{number(o.price)}} IQD</td><td><select v-model="o.status" @change="updateStatus(o)" :aria-label="'حالة '+o.id"><option>مكتمل</option><option>قيد المراجعة</option><option>ملغي</option></select></td><td><button @click="show('order',o)" class="admin-row-action" :aria-label="'تفاصيل '+o.id"><Eye :size="17"/></button></td></tr></tbody></table></div></section></template>
  <template v-if="section==='customers'||section==='merchants'"><div class="admin-toolbar"><div class="admin-search"><Search :size="18"/><input v-model="query" placeholder="الاسم، الإيميل أو رقم الهاتف..." aria-label="البحث في العملاء"/></div><span>{{number(people.length)}} حساب</span></div><section class="admin-panel"><div v-if="!people.length" class="admin-empty"><Users/><h3>{{section==='merchants'?'محلاتك تبدأ من هنا':'عملاؤك راح يظهرون هنا'}}</h3><p>الحسابات المنشأة بالتطبيق تظهر تلقائياً خلال الجلسة.</p><button class="admin-secondary" @click="show('customer')">إضافة حساب تجريبي</button></div><div v-else class="admin-table-wrap"><table><thead><tr><th>الاسم</th><th>رقم الهاتف</th><th>الإيميل</th><th>نوع الحساب</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody><tr v-for="c in people"><td>{{c.name}}<small dir="ltr">{{c.date}}</small></td><td dir="ltr">{{c.phone}}</td><td dir="ltr">{{c.email}}</td><td>{{c.kind}}</td><td><span class="admin-status" :class="{muted:!c.active}">{{c.active?'نشط':'موقوف'}}</span></td><td><button class="admin-row-action" @click="show('customer',c)" :aria-label="'تعديل '+c.name"><Pencil :size="16"/> تعديل</button></td></tr></tbody></table></div></section></template>
  <template v-if="section==='payments'"><div class="admin-mini-stats"><div><span>قيمة عمليات المحاكاة</span><b>{{number(gross)}} <small>IQD</small></b></div><div><span>عمليات المحاكاة</span><b>{{number(store.orders.length)}}</b></div><div><span>التحصيل الحقيقي</span><b>0 <small>IQD</small></b></div></div><section class="admin-panel admin-integration"><span class="admin-qi">Qi</span><div><h2>بوابة الدفع Qi</h2><p>مسار الدفع ظاهر بالتطبيق. الربط والتحصيل الفعلي بعد ما مفعّل.</p><span class="admin-status warning">بانتظار ربط آمن بالخادم</span></div><button class="admin-secondary" @click="go('settings')">إعدادات المتجر <ChevronLeft :size="15"/></button></section><section class="admin-panel"><div class="admin-panel-title"><h2>حركة المدفوعات التجريبية</h2><button @click="go('orders')">عرض الطلبات</button></div><div v-if="!store.orders.length" class="admin-empty compact">ماكو حركات دفع تجريبية بعد.</div><div class="admin-payment-row" v-for="o in store.orders"><CreditCard :size="20"/><div><b>{{o.customer}}</b><small dir="ltr">{{o.id}} · {{o.date}}</small></div><span class="admin-status">محاكاة فقط</span><b dir="ltr">{{number(o.price)}} IQD</b></div></section></template>
  <template v-if="section==='suppliers'"><div class="admin-info-box"><Link :size="20"/><p>أضف أسماء مورّدي Excel وAPI ونظّمهم هنا. الاتصال بالمورّدين ومفاتيح API تُجهّز لاحقاً على الخادم.</p></div><div v-if="!store.suppliers.length" class="admin-panel admin-empty"><Link/><h3>مصادر كارتاتك، بمكان واحد</h3><p>أضف أول مورّد وحدّد طريقة تجهيز البطاقات.</p><button class="admin-secondary" @click="show('supplier')">إضافة مورّد</button></div><div class="admin-supplier-grid"><article v-for="v in store.suppliers" class="admin-panel"><span class="admin-supplier-icon"><Link v-if="v.method==='API'"/><Upload v-else/></span><h2>{{v.name}}</h2><p>{{v.method==='API'?'تجهيز بواسطة API':'ملفات Excel'}}</p><span class="admin-status" :class="{muted:!v.active}">{{v.active?'مفعّل بالمعاينة':'موقوف'}}</span><small v-if="v.url" dir="ltr">{{v.url}}</small><button class="admin-secondary" @click="show('supplier',v)">تعديل المورّد</button></article></div></template>
  <template v-if="section==='support'"><div class="admin-toolbar"><div class="admin-search"><Search :size="18"/><input v-model="query" placeholder="ابحث بعنوان التذكرة أو العميل..." aria-label="البحث في التذاكر"/></div><select v-model="filter" aria-label="تصفية التذاكر حسب الحالة"><option v-for="s in ['الكل','مفتوحة','قيد المعالجة','مغلقة']">{{s}}</option></select></div><section class="admin-panel"><div v-if="!tickets.length" class="admin-empty"><Headphones/><h3>كل استفسار إله مكان</h3><p>التذاكر المضافة من قسم الدعم بالتطبيق تظهر هنا.</p></div><div v-for="t in tickets" class="admin-ticket"><div><span class="admin-status">{{t.status}}</span><h3>{{t.subject}}</h3><p>{{t.message}}</p><small>{{t.customer}} · <span dir="ltr">{{t.id}} / {{t.date}}</span></small></div><button class="admin-secondary" @click="show('ticket',t)">فتح التذكرة <ChevronLeft :size="16"/></button></div></section></template>
  <template v-if="section==='settings'"><div class="admin-two-columns"><form class="admin-panel admin-settings" @submit.prevent="saveSettings"><div class="admin-panel-title"><h2>معلومات المتجر</h2></div><label>اسم المتجر<input v-model="settings.name" required maxlength="60"/></label><label>إيميل الدعم<input v-model="settings.supportEmail" type="email" dir="ltr" placeholder="support@example.com"/></label><label>رقم الدعم<input v-model="settings.supportPhone" type="tel" dir="ltr" placeholder="07XXXXXXXXX"/></label><label>حد تنبيه المخزون<input v-model.number="settings.lowStock" type="number" min="0" max="10000" required dir="ltr"/></label><button class="admin-primary">حفظ الإعدادات التجريبية</button></form><section class="admin-panel admin-settings-summary"><div class="admin-panel-title"><h2>بنية التطبيق</h2></div><div><span>الواجهة</span><b>Vue 3 / PWA</b></div><div><span>اللغة</span><b>العربية / RTL</b></div><div><span>الخط</span><b>Cairo Bold / 700</b></div><div><span>الأرقام</span><b>English / 0–9</b></div><div><span>التواريخ</span><b dir="ltr">YYYY-MM-DD</b></div><div><span>الدفع</span><b>Qi / محاكاة</b></div><p class="admin-info-text">هذه لوحة معاينة عامة، وما بيها صلاحيات إدارة حقيقية. حماية الدخول وحفظ البيانات وربط Qi وAPI تحتاج خادماً قبل التشغيل التجاري.</p></section></div></template>
  <footer class="admin-footer"><span>ماسال / مساحة الإدارة</span><span dir="ltr">VUE PWA · DEMO SESSION</span></footer>
  </div></main>
  <div v-if="notice" class="admin-notice" role="status">{{notice}}</div>
  <dialog ref="dialog" class="admin-dialog" @cancel="modal=null" @click="e=>{if(e.target===dialog)close()}"><button class="admin-dialog-close" @click="close" aria-label="إغلاق"><X :size="20"/></button><span class="admin-eyebrow">MASAL / MANAGE</span><h2>{{modal==='product'?(draft.id?'تعديل بطاقة':'إضافة بطاقة'):modal==='customer'?'بيانات الحساب':modal==='supplier'?'بيانات المورّد':modal==='ticket'?'تفاصيل التذكرة':'تفاصيل الطلب'}}</h2>
    <form v-if="modal!=='order'" class="admin-dialog-form" @submit.prevent="save">
      <template v-if="modal==='product'"><div class="admin-form-grid"><label>اسم البطاقة<input v-model="draft.name" required maxlength="60"/></label><label>الاسم الإنجليزي<input v-model="draft.en" required maxlength="24" dir="ltr"/></label><label>التصنيف<select v-model="draft.category"><option>اتصالات</option><option>ألعاب</option><option>عالمية</option></select></label><label>وصف قصير<input v-model="draft.tag" required maxlength="40"/></label></div><label>لون البطاقة<input v-model="draft.color" type="color"/></label><div class="admin-denom-title"><b>الفئات والأسعار / IQD</b><button type="button" @click="addDenom"><Plus :size="16"/> فئة</button></div><div class="admin-denom-head"><span>الفئة</span><span>الأفراد</span><span>المحلات</span><span></span></div><div class="admin-denom-row" v-for="(v,i) in draft.values"><input v-model.number="draft.values[i]" type="number" min="1" required :aria-label="'قيمة الفئة '+(i+1)"/><input v-model.number="draft.prices[i]" type="number" min="1" required :aria-label="'سعر الأفراد '+(i+1)"/><input v-model.number="draft.wholesale[i]" type="number" min="1" required :aria-label="'سعر المحلات '+(i+1)"/><button type="button" @click="removeDenom(i)" :disabled="draft.values.length===1" :aria-label="'حذف الفئة '+(i+1)"><X :size="16"/></button></div><label class="admin-checkbox"><input v-model="draft.active" type="checkbox"/> نشر البطاقة بالتطبيق</label></template>
      <template v-if="modal==='customer'"><label>الاسم<input v-model="draft.name" required maxlength="80"/></label><label>رقم الهاتف<input v-model="draft.phone" type="tel" required dir="ltr"/></label><label>الإيميل<input v-model="draft.email" type="email" required dir="ltr"/></label><label>نوع الحساب<select v-model="draft.kind"><option>فرد</option><option>محل</option></select></label><label class="admin-checkbox"><input v-model="draft.active" type="checkbox"/> حساب نشط بالمعاينة</label><p class="admin-info-text">إضافة سجل العميل هنا لا تنشئ باسورد دخول. جرّب إنشاء الحساب من التطبيق.</p></template>
      <template v-if="modal==='supplier'"><label>اسم المورّد<input v-model="draft.name" required maxlength="80"/></label><label>طريقة التزويد<select v-model="draft.method"><option>Excel</option><option>API</option></select></label><label v-if="draft.method==='API'">عنوان API<input v-model="draft.url" type="url" dir="ltr" placeholder="https://api.example.com" required/></label><label class="admin-checkbox"><input v-model="draft.active" type="checkbox"/> مفعّل بالمعاينة</label><p class="admin-info-text">الرابط يُحفظ كإعداد للجلسة فقط، بدون إرسال طلبات أو تخزين مفاتيح سرية.</p></template>
      <template v-if="modal==='ticket'"><div class="admin-ticket-message"><b>{{draft.subject}}</b><p>{{draft.message}}</p><small>{{draft.customer}} · {{draft.date}}</small></div><label>حالة التذكرة<select v-model="draft.status"><option>مفتوحة</option><option>قيد المعالجة</option><option>مغلقة</option></select></label><label>رد الإدارة<textarea v-model="draft.reply" rows="4" maxlength="2000" placeholder="اكتب ردك للمعاينة..."></textarea></label></template>
      <p v-if="formError" class="admin-form-error" role="alert">{{formError}}</p><button class="admin-primary">حفظ التغييرات</button>
    </form>
    <div v-if="modal==='order'" class="admin-order-details"><div><span>رقم الطلب</span><b dir="ltr">{{draft.id}}</b></div><div><span>العميل</span><b>{{draft.customer}}</b></div><div><span>البطاقة</span><b>{{draft.name}}</b></div><div><span>الفئة × الكمية</span><b>{{number(draft.value)}} × {{number(draft.quantity)}}</b></div><div><span>المجموع</span><b dir="ltr">{{number(draft.price)}} IQD</b></div><div><span>الدفع</span><b>{{draft.payment}}</b></div><div><span>التاريخ</span><b dir="ltr">{{draft.date}}</b></div><div><span>الحالة</span><b>{{draft.status}}</b></div><p class="admin-info-text">طلب تجريبي بدون خصم أموال أو إصدار أكواد حقيقية.</p></div>
  </dialog>
  </div>`
};
