import {createApp,ref,computed,nextTick} from 'vue/dist/vue.esm-bundler.js';
import {Home,Grid2X2,ShoppingBag,Headphones,Search,ChevronLeft,X,Check,Copy,CreditCard,Gamepad2,Smartphone,Layers,User,Plus,Minus,ShieldCheck,SlidersHorizontal,Ticket,ArrowUpRight} from 'lucide-vue-next';
import './style.css';
const app=createApp({
components:{Home,Grid2X2,ShoppingBag,Headphones,Search,ChevronLeft,X,Check,Copy,CreditCard,Gamepad2,Smartphone,Layers,User,Plus,Minus,ShieldCheck,SlidersHorizontal,Ticket,ArrowUpRight},
setup(){
const page=ref('home'),category=ref('الكل'),query=ref(''),merchant=ref(false),selected=ref(null),quantity=ref(1),denom=ref(0),orders=ref([]),toast=ref(''),subject=ref(''),message=ref(''),success=ref(false),dialog=ref(null);
const products=[{id:1,name:'زين العراق',en:'Zain',category:'اتصالات',color:'#173f39',tag:'الأكثر طلباً',values:[5000,10000,25000],prices:[5250,10500,25800]}, {id:2,name:'آسياسيل',en:'asiacell',category:'اتصالات',color:'#c1343a',tag:'شحن رصيد',values:[5000,10000,25000],prices:[5250,10400,25800]}, {id:3,name:'ببجي موبايل',en:'PUBG',category:'ألعاب',color:'#282d3b',tag:'شدّات UC',values:[60,325,660],prices:[1500,7500,14500]}, {id:4,name:'Apple',en:'Apple',category:'عالمية',color:'#4b4550',tag:'المتجر الأمريكي',values:[10,25,50],prices:[15500,38500,76500]}, {id:5,name:'الرابعة',en:'AL RABIAA',category:'اتصالات',color:'#7749a5',tag:'بطاقات تعبئة',values:[5000,10000,25000],prices:[5250,10500,26000]}, {id:6,name:'PlayStation',en:'PS',category:'ألعاب',color:'#254c9a',tag:'المتجر الأمريكي',values:[10,25,50],prices:[15500,38500,76500]}, {id:7,name:'كورك',en:'KOREK',category:'اتصالات',color:'#0076aa',tag:'شحن رصيد',values:[5000,10000,25000],prices:[5200,10400,25800]}, {id:8,name:'Steam',en:'STEAM',category:'عالمية',color:'#203447',tag:'المتجر الأمريكي',values:[5,10,20],prices:[8000,15500,31000]}];
const number=n=>new Intl.NumberFormat('en-US').format(n);
const filtered=computed(()=>products.filter(p=>(category.value==='الكل'||p.category===category.value)&&(`${p.name} ${p.en}`.toLowerCase().includes(query.value.toLowerCase()))));
const price=computed(()=>selected.value?selected.value.prices[denom.value]*quantity.value:0);
const nav=[{id:'home',label:'الرئيسية',icon:'Home'},{id:'cards',label:'البطاقات',icon:'Grid2X2'},{id:'orders',label:'مشترياتي',icon:'ShoppingBag'},{id:'support',label:'الدعم',icon:'Headphones'}];
function go(p){page.value=p;query.value='';window.scrollTo({top:0,behavior:'smooth'});}
function notify(t){toast.value=t;setTimeout(()=>toast.value='',3000)}
async function open(p){selected.value=p;quantity.value=1;denom.value=0;success.value=false;await nextTick();dialog.value.showModal()}
function close(){dialog.value.close();selected.value=null}
function buy(){orders.value.unshift({id:`DEMO-${String(orders.value.length+1).padStart(4,'0')}`,name:selected.value.name,value:selected.value.values[denom.value],price:price.value,quantity:quantity.value,date:new Date().toISOString().slice(0,10)});success.value=true}
function support(){notify('تمت معاينة رسالتك محلياً — لم تُرسل إلى فريق دعم');subject.value='';message.value=''}
async function copy(){try{await navigator.clipboard.writeText('DEMO-NOT-REDEEMABLE');notify('تم نسخ الكود التجريبي')}catch{notify('تعذّر النسخ. الكود: DEMO-NOT-REDEEMABLE')}}
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'browse_cards',description:'Filter demo cards in the visible catalog; does not purchase.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},execute:async input=>{if(typeof input.query!=='string')throw Error('query must be a string');page.value='cards';query.value=input.query;await nextTick();return filtered.value.map(p=>({id:p.id,name:p.name}))}})}catch{}}
return {page,category,query,merchant,selected,quantity,denom,orders,toast,subject,message,success,dialog,products,number,filtered,price,nav,go,notify,open,close,buy,support,copy};
},
template:`
<div class="app-shell">
<aside class="sidebar"><a class="brand" href="#" @click.prevent="go('home')"><span class="brand-mark"><Layers/></span><span>ماسال<small>DIGITAL STORE</small></span></a><div class="side-label">مساحتك الرقمية</div><nav><button v-for="n in nav" :class="{active:page===n.id}" @click="go(n.id)"><component :is="n.icon"/><span>{{n.label}}</span><ChevronLeft/></button></nav><div class="side-bottom"><ShieldCheck/><p>بطاقاتك، بمكان واحد</p><small>نسخة أولية للمعاينة</small></div></aside>
<main><header><div class="mobile-brand"><span class="brand-mark"><Layers/></span>ماسال</div><div class="breadcrumb">المتجر <ChevronLeft/> <span>{{nav.find(n=>n.id===page).label}}</span></div><div class="header-actions"><span class="preview-badge">معاينة تجريبية</span><button class="profile" @click="merchant=!merchant" :aria-label="merchant?'التبديل إلى حساب فرد':'التبديل إلى حساب محل'"><User/><span>{{merchant?'حساب محل':'حساب فرد'}}</span></button></div></header>
<div class="content"><Transition name="view" mode="out-in"><div :key="page">
<template v-if="page==='home'"><div class="welcome"><div><span class="eyebrow">كل اللي تحتاجه، أقرب إلك</span><h1>شنو نعبّي اليوم؟</h1></div><span class="edition" dir="ltr">YOUR DIGITAL EVERYDAY</span></div>
<div class="hero"><div class="hero-copy"><span class="hero-label"><span></span> رصيد • ألعاب • بطاقات عالمية</span><h2>عالمك الرقمي.<br><span>على كيفك.</span></h2><p>اختار بطاقتك، وحدّد فئتها.<br>كل خياراتك بمكان واحد.</p><button @click="go('cards')">تصفّح البطاقات <Grid2X2 :size="18"/></button></div><div class="hero-feature"><div class="feature-top"><CreditCard/><span>DIGITAL / 01</span></div><span class="feature-title">اختيارات أكثر.<br>خطوات أقل.</span><div class="feature-bottom"><span>اتصالات</span><span>ألعاب</span><span>عالمية</span></div></div></div>
<section class="brands-section"><div class="section-title"><h2>شركاتك المفضّلة</h2><button @click="go('cards')">عرض الكل <ChevronLeft :size="16"/></button></div><div class="brands"><button v-for="p in products.slice(0,6)" @click="open(p)"><span class="brand-logo" :style="{color:p.color}">{{p.en}}</span><span>{{p.name}}</span></button></div></section>
<div class="section-title"><div><span class="eyebrow">اختيارات يومية</span><h2>بطاقات تستاهل مكانها</h2></div><button @click="go('cards')">كل البطاقات <ChevronLeft :size="16"/></button></div><div class="product-grid"><article class="product" v-for="p in products.slice(0,4)"><div class="product-art" :style="{'--card-color':p.color}"><span>{{p.tag}}</span><strong dir="ltr">{{p.en}}</strong><small>DIGITAL GIFT CARD</small></div><div class="product-info"><h3>{{p.name}}</h3><span class="muted">{{p.values.length}} فئات متوفرة</span><div class="product-footer"><span><small>يبدأ من</small><b>{{number(p.prices[0])}} <small>د.ع</small></b></span><button @click="open(p)" :aria-label="'شراء '+p.name"><Plus :size="20"/></button></div></div></article></div></template>
<template v-if="page==='cards'"><span class="eyebrow">اختار اللي يناسبك</span><h1>اكتشف البطاقات</h1><div class="search"><Search/><input v-model="query" placeholder="ابحث عن شركة أو بطاقة..." aria-label="البحث عن بطاقة"/></div><div class="filters"><button v-for="c in ['الكل','اتصالات','ألعاب','عالمية']" :class="{selected:category===c}" @click="category=c">{{c}}</button><span>{{number(filtered.length)}} بطاقات</span></div><div class="merchant-note" v-if="merchant">معاينة حساب محل — الأسعار المعروضة تجريبية، وتسعير الجملة يُحدّد لاحقاً.</div><div class="product-grid"><article class="product" v-for="p in filtered"><div class="product-art" :style="{'--card-color':p.color}"><span>{{p.tag}}</span><strong dir="ltr">{{p.en}}</strong><small>DIGITAL GIFT CARD</small></div><div class="product-info"><h3>{{p.name}}</h3><span class="muted">{{number(p.values.length)}} فئات متوفرة</span><div class="product-footer"><span><small>يبدأ من</small><b>{{number(p.prices[0])}} <small>د.ع</small></b></span><button @click="open(p)" :aria-label="'شراء '+p.name"><Plus/></button></div></div></article></div><div class="empty" v-if="!filtered.length"><Search/><h2>ما لقينا بطاقة بهالاسم</h2><button class="primary" @click="query='';category='الكل'">عرض كل البطاقات</button></div></template>
<template v-if="page==='orders'"><span class="eyebrow">كل بطاقاتك هنا</span><h1>مشترياتي</h1><div v-if="!orders.length" class="empty"><ShoppingBag/><h2>أول بطاقة بانتظارك</h2><p>جرّب شراء بطاقة حتى تشوف شكل طلباتك هنا.</p><button class="primary" @click="go('cards')">اكتشف البطاقات</button></div><div class="order" v-for="o in orders"><div><span class="status">طلب تجريبي</span><h2>{{o.name}} · {{number(o.value)}}</h2><small dir="ltr">{{o.id}} · {{o.date}}</small></div><b>{{number(o.price)}} د.ع</b><button @click="copy"><Copy :size="18"/> نسخ كود تجريبي</button></div></template>
<template v-if="page==='support'"><span class="eyebrow">نسمعك ونساعدك</span><h1>الدعم والمساعدة</h1><div class="support-layout"><form class="support-form" @submit.prevent="support"><h2>شلون نكدر نساعدك؟</h2><label>عنوان الرسالة<input v-model="subject" required maxlength="100" placeholder="اكتب موضوع استفسارك"/></label><label>رسالتك<textarea v-model="message" required maxlength="2000" rows="5" placeholder="احچيلنا التفاصيل..."></textarea></label><p class="muted">نموذج معاينة فقط، الرسائل لا تُرسل.</p><button class="primary">معاينة إرسال الرسالة</button></form><div class="faq"><Headphones :size="36"/><h2>إجابات سريعة</h2><details><summary>وين ألكى الكارت بعد الشراء؟</summary><p>بقسم مشترياتي، تگدر تشوف تفاصيل الطلب وتنسخ الكود.</p></details><details><summary>شنو طرق الدفع؟</summary><p>الدفع المخطط له عبر Qi. الدفع الحالي محاكاة بدون خصم أموال.</p></details><details><summary>هل الأسعار نهائية؟</summary><p>لا، الأسعار والمنتجات بهذه النسخة لغرض المعاينة.</p></details></div></div></template>
</div></Transition><footer><span>ماسال <span class="dot">/</span> MASAL</span><span dir="ltr">PREVIEW — 2026</span></footer></div></main>
<nav class="bottom-nav"><button v-for="n in nav" :class="{active:page===n.id}" @click="go(n.id)"><component :is="n.icon" :size="21"/><span>{{n.label}}</span></button></nav>
<dialog ref="dialog" @click="e=>{if(e.target===dialog)close()}" @cancel="selected=null"><template v-if="selected"><button class="close" @click="close" aria-label="إغلاق"><X/></button><template v-if="!success"><span class="eyebrow">خلّص اختيارك</span><h2>{{selected.name}}</h2><p class="muted">{{selected.tag}}</p><label class="field-label">فئة البطاقة</label><div class="denominations"><button v-for="(v,i) in selected.values" :class="{selected:denom===i}" @click="denom=i">{{number(v)}} <small>{{selected.id===3?'UC':selected.category==='اتصالات'?'د.ع':'USD'}}</small></button></div><div class="quantity-row"><span>الكمية</span><div class="stepper"><button :disabled="quantity<=1" @click="quantity--" aria-label="تقليل الكمية"><Minus :size="18"/></button><span>{{number(quantity)}}</span><button :disabled="quantity>=20" @click="quantity++" aria-label="زيادة الكمية"><Plus :size="18"/></button></div></div><div class="payment"><CreditCard/><span>الدفع بواسطة Qi<small>محاكاة للدفع فقط</small></span><Check :size="18"/></div><div class="total"><span>المجموع</span><strong>{{number(price)}} <small>د.ع</small></strong></div><button class="primary wide" @click="buy">تجربة الشراء</button><p class="dialog-note">لا يتم خصم أي مبلغ أو إصدار كارت حقيقي.</p></template><template v-else><div class="success"><span><Check :size="36"/></span><h2>اكتملت التجربة!</h2><p>أضفنا طلبك التجريبي إلى مشترياتي.</p><button class="primary wide" @click="close();go('orders')">عرض مشترياتي</button></div></template></template></dialog>
<Transition name="toast"><div v-if="toast" class="toast" role="status">{{toast}}</div></Transition>
</div>`});app.mount('#app');

